version: '3.8'
services:
  web:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: db.env
    ports:
      - 8080:8080
    networks:
      - server_client
    volumes:
      - ./:/app
    depends_on:
      mysql-test:
        condition: service_healthy
  mysql-test:
    container_name: mysql
    image: mysql
    restart: always
    env_file: db.env
    networks:
      - server_client
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql_volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  server_client:
